package export

const fileTpl = `///
// Code generated by protoc-gen-dart-export. DO NOT EDIT!
//
{{ range $_, $file := . }}
{{- $name := $file.InputPath.BaseName }}
{{- if $file.Messages }}
export './src/generated/{{ $name }}.pb.dart';
{{- end }}
{{- if $file.Enums }}
export './src/generated/{{ $name }}.pbenum.dart';
{{- end }}
{{- if $file.Services }}
export './src/generated/{{ $name }}.pbgrpc.dart';
{{- end }}
{{- if $file.Messages }}
export './src/generated/{{ $name }}.pbjson.dart';
{{- end }}
{{- end }}
`
