package golang

const fileTpl = `// Code generated by protoc-gen-auth. DO NOT EDIT.
// source: {{ .InputPath }}
package {{ pkg . }}

import 	"github.com/youlu-cn/grpc-gen/protoc-gen-auth/auth"

// Reference imports to suppress errors if they are not otherwise used.
var _ = auth.AccessLevel__NO_LIMIT

{{ range .Services }}
{{ template "service" . }}
{{end}}
`
