// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth/annotations.proto

package com.github.grpc-gen.auth;

public final class Annotations {
  private Annotations() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.github.grpc-gen.auth.Annotations.access);
    registry.add(com.github.grpc-gen.auth.Annotations.visible);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code auth.AccessLevel}
   */
  public enum AccessLevel
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Public access.
     * </pre>
     *
     * <code>_NO_LIMIT = 0;</code>
     */
    _NO_LIMIT(0),
    /**
     * <pre>
     * Lower access required.
     * </pre>
     *
     * <code>LOW_ACCESS_LEVEL = 100;</code>
     */
    LOW_ACCESS_LEVEL(100),
    /**
     * <pre>
     * Middle access required.
     * </pre>
     *
     * <code>MIDDLE_ACCESS_LEVEL = 200;</code>
     */
    MIDDLE_ACCESS_LEVEL(200),
    /**
     * <pre>
     * High access required.
     * </pre>
     *
     * <code>HIGH_ACCESS_LEVEL = 300;</code>
     */
    HIGH_ACCESS_LEVEL(300),
    /**
     * <pre>
     * For server internal only.
     * </pre>
     *
     * <code>SERVER_INTERNAL = 400;</code>
     */
    SERVER_INTERNAL(400),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Public access.
     * </pre>
     *
     * <code>_NO_LIMIT = 0;</code>
     */
    public static final int _NO_LIMIT_VALUE = 0;
    /**
     * <pre>
     * Lower access required.
     * </pre>
     *
     * <code>LOW_ACCESS_LEVEL = 100;</code>
     */
    public static final int LOW_ACCESS_LEVEL_VALUE = 100;
    /**
     * <pre>
     * Middle access required.
     * </pre>
     *
     * <code>MIDDLE_ACCESS_LEVEL = 200;</code>
     */
    public static final int MIDDLE_ACCESS_LEVEL_VALUE = 200;
    /**
     * <pre>
     * High access required.
     * </pre>
     *
     * <code>HIGH_ACCESS_LEVEL = 300;</code>
     */
    public static final int HIGH_ACCESS_LEVEL_VALUE = 300;
    /**
     * <pre>
     * For server internal only.
     * </pre>
     *
     * <code>SERVER_INTERNAL = 400;</code>
     */
    public static final int SERVER_INTERNAL_VALUE = 400;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AccessLevel valueOf(int value) {
      return forNumber(value);
    }

    public static AccessLevel forNumber(int value) {
      switch (value) {
        case 0: return _NO_LIMIT;
        case 100: return LOW_ACCESS_LEVEL;
        case 200: return MIDDLE_ACCESS_LEVEL;
        case 300: return HIGH_ACCESS_LEVEL;
        case 400: return SERVER_INTERNAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AccessLevel>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AccessLevel> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AccessLevel>() {
            public AccessLevel findValueByNumber(int number) {
              return AccessLevel.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.grpc-gen.auth.Annotations.getDescriptor().getEnumTypes().get(0);
    }

    private static final AccessLevel[] VALUES = values();

    public static AccessLevel valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AccessLevel(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:auth.AccessLevel)
  }

  /**
   * Protobuf enum {@code auth.VisibleScope}
   */
  public enum VisibleScope
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Public service scope.
     * </pre>
     *
     * <code>PUBLIC_SCOPE = 0;</code>
     */
    PUBLIC_SCOPE(0),
    /**
     * <pre>
     * Internal service scope.
     * </pre>
     *
     * <code>INTERNAL_SCOPE = 1;</code>
     */
    INTERNAL_SCOPE(1),
    /**
     * <pre>
     * Public &amp; Internal.
     * </pre>
     *
     * <code>ALL_SCOPE = 2;</code>
     */
    ALL_SCOPE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Public service scope.
     * </pre>
     *
     * <code>PUBLIC_SCOPE = 0;</code>
     */
    public static final int PUBLIC_SCOPE_VALUE = 0;
    /**
     * <pre>
     * Internal service scope.
     * </pre>
     *
     * <code>INTERNAL_SCOPE = 1;</code>
     */
    public static final int INTERNAL_SCOPE_VALUE = 1;
    /**
     * <pre>
     * Public &amp; Internal.
     * </pre>
     *
     * <code>ALL_SCOPE = 2;</code>
     */
    public static final int ALL_SCOPE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static VisibleScope valueOf(int value) {
      return forNumber(value);
    }

    public static VisibleScope forNumber(int value) {
      switch (value) {
        case 0: return PUBLIC_SCOPE;
        case 1: return INTERNAL_SCOPE;
        case 2: return ALL_SCOPE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<VisibleScope>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        VisibleScope> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<VisibleScope>() {
            public VisibleScope findValueByNumber(int number) {
              return VisibleScope.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.grpc-gen.auth.Annotations.getDescriptor().getEnumTypes().get(1);
    }

    private static final VisibleScope[] VALUES = values();

    public static VisibleScope valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private VisibleScope(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:auth.VisibleScope)
  }

  public interface AccessOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.Access)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.auth.AccessLevel level = 1;</code>
     */
    int getLevelValue();
    /**
     * <code>.auth.AccessLevel level = 1;</code>
     */
    com.github.grpc-gen.auth.Annotations.AccessLevel getLevel();
  }
  /**
   * Protobuf type {@code auth.Access}
   */
  public  static final class Access extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:auth.Access)
      AccessOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Access.newBuilder() to construct.
    private Access(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Access() {
      level_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Access(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              level_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.grpc-gen.auth.Annotations.internal_static_auth_Access_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.grpc-gen.auth.Annotations.internal_static_auth_Access_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.grpc-gen.auth.Annotations.Access.class, com.github.grpc-gen.auth.Annotations.Access.Builder.class);
    }

    public static final int LEVEL_FIELD_NUMBER = 1;
    private int level_;
    /**
     * <code>.auth.AccessLevel level = 1;</code>
     */
    public int getLevelValue() {
      return level_;
    }
    /**
     * <code>.auth.AccessLevel level = 1;</code>
     */
    public com.github.grpc-gen.auth.Annotations.AccessLevel getLevel() {
      @SuppressWarnings("deprecation")
      com.github.grpc-gen.auth.Annotations.AccessLevel result = com.github.grpc-gen.auth.Annotations.AccessLevel.valueOf(level_);
      return result == null ? com.github.grpc-gen.auth.Annotations.AccessLevel.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (level_ != com.github.grpc-gen.auth.Annotations.AccessLevel._NO_LIMIT.getNumber()) {
        output.writeEnum(1, level_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (level_ != com.github.grpc-gen.auth.Annotations.AccessLevel._NO_LIMIT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, level_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.grpc-gen.auth.Annotations.Access)) {
        return super.equals(obj);
      }
      com.github.grpc-gen.auth.Annotations.Access other = (com.github.grpc-gen.auth.Annotations.Access) obj;

      if (level_ != other.level_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + level_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.grpc-gen.auth.Annotations.Access parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.grpc-gen.auth.Annotations.Access parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.grpc-gen.auth.Annotations.Access parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.grpc-gen.auth.Annotations.Access parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.grpc-gen.auth.Annotations.Access parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.grpc-gen.auth.Annotations.Access parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.grpc-gen.auth.Annotations.Access parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.grpc-gen.auth.Annotations.Access parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.grpc-gen.auth.Annotations.Access parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.grpc-gen.auth.Annotations.Access parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.grpc-gen.auth.Annotations.Access parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.grpc-gen.auth.Annotations.Access parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.grpc-gen.auth.Annotations.Access prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code auth.Access}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.Access)
        com.github.grpc-gen.auth.Annotations.AccessOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.grpc-gen.auth.Annotations.internal_static_auth_Access_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.grpc-gen.auth.Annotations.internal_static_auth_Access_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.grpc-gen.auth.Annotations.Access.class, com.github.grpc-gen.auth.Annotations.Access.Builder.class);
      }

      // Construct using com.github.grpc-gen.auth.Annotations.Access.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        level_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.grpc-gen.auth.Annotations.internal_static_auth_Access_descriptor;
      }

      @java.lang.Override
      public com.github.grpc-gen.auth.Annotations.Access getDefaultInstanceForType() {
        return com.github.grpc-gen.auth.Annotations.Access.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.grpc-gen.auth.Annotations.Access build() {
        com.github.grpc-gen.auth.Annotations.Access result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.grpc-gen.auth.Annotations.Access buildPartial() {
        com.github.grpc-gen.auth.Annotations.Access result = new com.github.grpc-gen.auth.Annotations.Access(this);
        result.level_ = level_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.grpc-gen.auth.Annotations.Access) {
          return mergeFrom((com.github.grpc-gen.auth.Annotations.Access)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.grpc-gen.auth.Annotations.Access other) {
        if (other == com.github.grpc-gen.auth.Annotations.Access.getDefaultInstance()) return this;
        if (other.level_ != 0) {
          setLevelValue(other.getLevelValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.grpc-gen.auth.Annotations.Access parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.grpc-gen.auth.Annotations.Access) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int level_ = 0;
      /**
       * <code>.auth.AccessLevel level = 1;</code>
       */
      public int getLevelValue() {
        return level_;
      }
      /**
       * <code>.auth.AccessLevel level = 1;</code>
       */
      public Builder setLevelValue(int value) {
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.auth.AccessLevel level = 1;</code>
       */
      public com.github.grpc-gen.auth.Annotations.AccessLevel getLevel() {
        @SuppressWarnings("deprecation")
        com.github.grpc-gen.auth.Annotations.AccessLevel result = com.github.grpc-gen.auth.Annotations.AccessLevel.valueOf(level_);
        return result == null ? com.github.grpc-gen.auth.Annotations.AccessLevel.UNRECOGNIZED : result;
      }
      /**
       * <code>.auth.AccessLevel level = 1;</code>
       */
      public Builder setLevel(com.github.grpc-gen.auth.Annotations.AccessLevel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        level_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.auth.AccessLevel level = 1;</code>
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:auth.Access)
    }

    // @@protoc_insertion_point(class_scope:auth.Access)
    private static final com.github.grpc-gen.auth.Annotations.Access DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.grpc-gen.auth.Annotations.Access();
    }

    public static com.github.grpc-gen.auth.Annotations.Access getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Access>
        PARSER = new com.google.protobuf.AbstractParser<Access>() {
      @java.lang.Override
      public Access parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Access(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Access> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Access> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.grpc-gen.auth.Annotations.Access getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VisibleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.Visible)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.auth.VisibleScope scope = 1;</code>
     */
    int getScopeValue();
    /**
     * <code>.auth.VisibleScope scope = 1;</code>
     */
    com.github.grpc-gen.auth.Annotations.VisibleScope getScope();
  }
  /**
   * Protobuf type {@code auth.Visible}
   */
  public  static final class Visible extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:auth.Visible)
      VisibleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Visible.newBuilder() to construct.
    private Visible(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Visible() {
      scope_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Visible(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              scope_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.grpc-gen.auth.Annotations.internal_static_auth_Visible_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.grpc-gen.auth.Annotations.internal_static_auth_Visible_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.grpc-gen.auth.Annotations.Visible.class, com.github.grpc-gen.auth.Annotations.Visible.Builder.class);
    }

    public static final int SCOPE_FIELD_NUMBER = 1;
    private int scope_;
    /**
     * <code>.auth.VisibleScope scope = 1;</code>
     */
    public int getScopeValue() {
      return scope_;
    }
    /**
     * <code>.auth.VisibleScope scope = 1;</code>
     */
    public com.github.grpc-gen.auth.Annotations.VisibleScope getScope() {
      @SuppressWarnings("deprecation")
      com.github.grpc-gen.auth.Annotations.VisibleScope result = com.github.grpc-gen.auth.Annotations.VisibleScope.valueOf(scope_);
      return result == null ? com.github.grpc-gen.auth.Annotations.VisibleScope.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (scope_ != com.github.grpc-gen.auth.Annotations.VisibleScope.PUBLIC_SCOPE.getNumber()) {
        output.writeEnum(1, scope_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (scope_ != com.github.grpc-gen.auth.Annotations.VisibleScope.PUBLIC_SCOPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, scope_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.grpc-gen.auth.Annotations.Visible)) {
        return super.equals(obj);
      }
      com.github.grpc-gen.auth.Annotations.Visible other = (com.github.grpc-gen.auth.Annotations.Visible) obj;

      if (scope_ != other.scope_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SCOPE_FIELD_NUMBER;
      hash = (53 * hash) + scope_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.grpc-gen.auth.Annotations.Visible parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.grpc-gen.auth.Annotations.Visible parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.grpc-gen.auth.Annotations.Visible parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.grpc-gen.auth.Annotations.Visible parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.grpc-gen.auth.Annotations.Visible parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.grpc-gen.auth.Annotations.Visible parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.grpc-gen.auth.Annotations.Visible parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.grpc-gen.auth.Annotations.Visible parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.grpc-gen.auth.Annotations.Visible parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.grpc-gen.auth.Annotations.Visible parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.grpc-gen.auth.Annotations.Visible parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.grpc-gen.auth.Annotations.Visible parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.grpc-gen.auth.Annotations.Visible prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code auth.Visible}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.Visible)
        com.github.grpc-gen.auth.Annotations.VisibleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.grpc-gen.auth.Annotations.internal_static_auth_Visible_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.grpc-gen.auth.Annotations.internal_static_auth_Visible_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.grpc-gen.auth.Annotations.Visible.class, com.github.grpc-gen.auth.Annotations.Visible.Builder.class);
      }

      // Construct using com.github.grpc-gen.auth.Annotations.Visible.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        scope_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.grpc-gen.auth.Annotations.internal_static_auth_Visible_descriptor;
      }

      @java.lang.Override
      public com.github.grpc-gen.auth.Annotations.Visible getDefaultInstanceForType() {
        return com.github.grpc-gen.auth.Annotations.Visible.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.grpc-gen.auth.Annotations.Visible build() {
        com.github.grpc-gen.auth.Annotations.Visible result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.grpc-gen.auth.Annotations.Visible buildPartial() {
        com.github.grpc-gen.auth.Annotations.Visible result = new com.github.grpc-gen.auth.Annotations.Visible(this);
        result.scope_ = scope_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.grpc-gen.auth.Annotations.Visible) {
          return mergeFrom((com.github.grpc-gen.auth.Annotations.Visible)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.grpc-gen.auth.Annotations.Visible other) {
        if (other == com.github.grpc-gen.auth.Annotations.Visible.getDefaultInstance()) return this;
        if (other.scope_ != 0) {
          setScopeValue(other.getScopeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.grpc-gen.auth.Annotations.Visible parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.grpc-gen.auth.Annotations.Visible) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int scope_ = 0;
      /**
       * <code>.auth.VisibleScope scope = 1;</code>
       */
      public int getScopeValue() {
        return scope_;
      }
      /**
       * <code>.auth.VisibleScope scope = 1;</code>
       */
      public Builder setScopeValue(int value) {
        scope_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.auth.VisibleScope scope = 1;</code>
       */
      public com.github.grpc-gen.auth.Annotations.VisibleScope getScope() {
        @SuppressWarnings("deprecation")
        com.github.grpc-gen.auth.Annotations.VisibleScope result = com.github.grpc-gen.auth.Annotations.VisibleScope.valueOf(scope_);
        return result == null ? com.github.grpc-gen.auth.Annotations.VisibleScope.UNRECOGNIZED : result;
      }
      /**
       * <code>.auth.VisibleScope scope = 1;</code>
       */
      public Builder setScope(com.github.grpc-gen.auth.Annotations.VisibleScope value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        scope_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.auth.VisibleScope scope = 1;</code>
       */
      public Builder clearScope() {
        
        scope_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:auth.Visible)
    }

    // @@protoc_insertion_point(class_scope:auth.Visible)
    private static final com.github.grpc-gen.auth.Annotations.Visible DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.grpc-gen.auth.Annotations.Visible();
    }

    public static com.github.grpc-gen.auth.Annotations.Visible getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Visible>
        PARSER = new com.google.protobuf.AbstractParser<Visible>() {
      @java.lang.Override
      public Visible parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Visible(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Visible> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Visible> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.grpc-gen.auth.Annotations.Visible getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ACCESS_FIELD_NUMBER = 2360;
  /**
   * <pre>
   * ID assigned by protobuf-global-extension-registry&#64;google.com for grpc-gateway project.
   * All IDs are the same, as assigned. It is okay that they are the same, as they extend
   * different descriptor messages.
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      com.github.grpc-gen.auth.Annotations.Access> access = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.github.grpc-gen.auth.Annotations.Access.class,
        com.github.grpc-gen.auth.Annotations.Access.getDefaultInstance());
  public static final int VISIBLE_FIELD_NUMBER = 1360;
  /**
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      com.github.grpc-gen.auth.Annotations.Visible> visible = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.github.grpc-gen.auth.Annotations.Visible.class,
        com.github.grpc-gen.auth.Annotations.Visible.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_Access_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_Access_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_Visible_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_Visible_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026auth/annotations.proto\022\004auth\032 google/p" +
      "rotobuf/descriptor.proto\"*\n\006Access\022 \n\005le" +
      "vel\030\001 \001(\0162\021.auth.AccessLevel\",\n\007Visible\022" +
      "!\n\005scope\030\001 \001(\0162\022.auth.VisibleScope*z\n\013Ac" +
      "cessLevel\022\r\n\t_NO_LIMIT\020\000\022\024\n\020LOW_ACCESS_L" +
      "EVEL\020d\022\030\n\023MIDDLE_ACCESS_LEVEL\020\310\001\022\026\n\021HIGH" +
      "_ACCESS_LEVEL\020\254\002\022\024\n\017SERVER_INTERNAL\020\220\003*C" +
      "\n\014VisibleScope\022\020\n\014PUBLIC_SCOPE\020\000\022\022\n\016INTE" +
      "RNAL_SCOPE\020\001\022\r\n\tALL_SCOPE\020\002:=\n\006access\022\036." +
      "google.protobuf.MethodOptions\030\270\022 \001(\0132\014.a" +
      "uth.Access:@\n\007visible\022\037.google.protobuf." +
      "ServiceOptions\030\320\n \001(\0132\r.auth.VisibleBR\n\030" +
      "com.github.grpc-gen.authZ6github.com/you" +
      "lu-cn/grpc-gen/protoc-gen-auth/auth;auth" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_auth_Access_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_auth_Access_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_Access_descriptor,
        new java.lang.String[] { "Level", });
    internal_static_auth_Visible_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_auth_Visible_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_Visible_descriptor,
        new java.lang.String[] { "Scope", });
    access.internalInit(descriptor.getExtensions().get(0));
    visible.internalInit(descriptor.getExtensions().get(1));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
