// Code generated by protoc-gen-auth. DO NOT EDIT!
// source: auth.proto
package example

import "github.com/appootb/grpc-gen/protoc-gen-auth/auth"

// Reference imports to suppress errors if they are not otherwise used.
var _ = auth.AccessLevel__NO_LIMIT

var _levelExample = map[string]auth.AccessLevel{
	"/example.Example/Test": auth.AccessLevel_LOW_ACCESS_LEVEL,
}

func AccessLevelOfExample(fullPath string) auth.AccessLevel {
	return _levelExample[fullPath]
}

// Register scoped gRPC server.
func RegisterExampleScopeServer(s auth.Service, srv interface{}) {
	for _, grpc := range s.ScopedGRPCServer(auth.VisibleScope_PUBLIC_SCOPE) {
		grpc.RegisterService(&_Example_serviceDesc, srv)
	}
}

// Register scoped gateway handler.
func RegisterExampleScopeHandler(s auth.Service) error {
	return s.RegisterGateway(auth.VisibleScope_PUBLIC_SCOPE, RegisterExampleHandler)

}
