// Code generated by protoc-gen-auth. DO NOT EDIT.
// source: auth.proto
package example

import "github.com/youlu-cn/grpc-gen/protoc-gen-auth/auth"

// Reference imports to suppress errors if they are not otherwise used.
var _ = auth.AccessLevel__NO_LIMIT

var _levelExample = map[string]auth.AccessLevel{
	"/example.Example/Test": auth.AccessLevel_LOW_ACCESS_LEVEL,
}

// Register scoped gRPC server.
func RegisterExampleScopeServer(a auth.Authenticator, s auth.Implementor, srv ExampleServer) error {
	// Set service access level.
	a.SetAccessLevel(_levelExample)

	// Register scoped gRPC server.
	for _, grpc := range s.ScopedGRPCServer(auth.VisibleScope_PUBLIC_SCOPE) {
		RegisterExampleServer(grpc, srv)
	}

	// Register scoped gateway handler.
	return s.RegisterGateway(auth.VisibleScope_PUBLIC_SCOPE, RegisterExampleHandler)

}
