// Code generated by protoc-gen-auth. DO NOT EDIT.
// source: auth.proto
package example

var _levelExample = map[string]int32{
	"/example.Example/test1": 1,
}

func AccessLevelOfExample(fullPath string) int32 {
	return _levelExample[fullPath]
}

var _levelExample2 = map[string]int32{
	"/example.Example2/test2": 2,
	"/example.Example2/test3": 3,
}

func AccessLevelOfExample2(fullPath string) int32 {
	return _levelExample2[fullPath]
}
