// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type External struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *External) Reset()         { *m = External{} }
func (m *External) String() string { return proto.CompactTextString(m) }
func (*External) ProtoMessage()    {}
func (*External) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *External) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_External.Unmarshal(m, b)
}
func (m *External) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_External.Marshal(b, m, deterministic)
}
func (m *External) XXX_Merge(src proto.Message) {
	xxx_messageInfo_External.Merge(m, src)
}
func (m *External) XXX_Size() int {
	return xxx_messageInfo_External.Size(m)
}
func (m *External) XXX_DiscardUnknown() {
	xxx_messageInfo_External.DiscardUnknown(m)
}

var xxx_messageInfo_External proto.InternalMessageInfo

func (m *External) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*External)(nil), "example.External")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 80 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8,
	0x49, 0x55, 0x92, 0xe2, 0xe2, 0x70, 0xad, 0x28, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0x11, 0xe2, 0xe3,
	0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c, 0x49, 0x62, 0x03,
	0xab, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x84, 0xae, 0xb5, 0x3b, 0x00, 0x00, 0x00,
}
