// Code generated by protoc-gen-auth. DO NOT EDIT.
// source: common.proto
package example

import "github.com/youlu-cn/grpc-gen/protoc-gen-auth/auth"

// Reference imports to suppress errors if they are not otherwise used.
var _ = auth.AccessLevel__NO_LIMIT
